# -*- coding: utf-8 -*-
"""Text-Classification-into-Thematic-Categories.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-jFVKFcBAUDHRYJohPNkMEzvmSKMPTX
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')


x_train_text = df_train['text']
y_train = df_train['label']


model = TfidfVectorizer(stop_words='english', max_features=5000)


x_train_v = model.fit_transform(x_train_text)


df_test_text = df_test['text']
x_test_v = model.transform(df_test_text)

model = RandomForestClassifier(n_estimators=200,
                             random_state=42,
                             n_jobs=-1)


model.fit(x_train_v, y_train)

y_pred = model.predict(x_test_v)

print(y_pred)

submission = pd.DataFrame({
    'SampleID': df_test['SampleID'],
    'label': y_pred
})
submission.to_csv('submission.csv', index=False)