# -*- coding: utf-8 -*-
"""The-National-Rabbit-Exhibition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_-EvlsovxZA4YDYB8FLzEF-RWmnNpv-
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.impute import SimpleImputer


df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")


map_sex = {"Mascul": 0, "Femelă": 1}
map_bool = {"True": 0, "False": 1, True: 0, False: 1}
map_culoare = {"Albastru": 0, "Havana": 1, "Alb": 2, "Negru": 3, "Agouti": 4}
map_calitate = {"Bună": 0, "Excelentă": 1, "Foarte_bună": 2}
map_forma = {"Incorectă": 0, "Aproape_corectă": 1, "Corectă": 2}
map_sanatate = {
    "Probleme_grave_de_sănătate": 0,
    "Ușoare_probleme_de_sănătate": 1,
    "Aspect_neîngrijit": 2,
    "Sănătos": 3
}

def apply_mappings(df):
    df["Sex"] = df["Sex"].map(map_sex)
    df["Ureche_lăsată"] = df["Ureche_lăsată"].map(map_bool)
    df["Culoare"] = df["Culoare"].map(map_culoare)
    df["Calitate_blană"] = df["Calitate_blană"].map(map_calitate)
    df["Formă_corp"] = df["Formă_corp"].map(map_forma)
    df["Apare_gușa"] = df["Apare_gușa"].map(map_bool)
    df["Sănătate"] = df["Sănătate"].map(map_sanatate)
    return df

df_train = apply_mappings(df_train)
df_test = apply_mappings(df_test)


condition = (
    (df_test['Sex'] == 1) &
    (df_test['Ureche_lăsată'] == 0) &
    (df_test['Culoare'] == 1)
)
num_rabbits = len(df_test[condition])


df_test['Cluster'] = -1
lop_mask = df_test['Ureche_lăsată'] == 0
erect_mask = df_test['Ureche_lăsată'] == 1


df_test.loc[lop_mask, 'Cluster'] = 0



X_erect = df_test.loc[erect_mask, ['Greutate', 'Lungime_urechi', 'Vârstă']].copy()

# Imputare și Scalare doar pe grupul Non-Lop
imputer_erect = SimpleImputer(strategy='median')
X_erect_imp = imputer_erect.fit_transform(X_erect)
scaler_erect = StandardScaler()
X_erect_scaled = scaler_erect.fit_transform(X_erect_imp)

# KMeans pentru a găsi celelalte 2 rase
kmeans_erect = KMeans(n_clusters=2, random_state=42, n_init=10)
erect_clusters = kmeans_erect.fit_predict(X_erect_scaled)

# Asignăm clusterii 1 și 2 grupului Non-Lop
df_test.loc[erect_mask, 'Cluster'] = erect_clusters + 1


target_col = None
potential_names = ['Scor_jurizare', 'Scor_judecată', 'judging_score', 'Judging Score', 'score', 'Scor']
for col in potential_names:
    if col in df_train.columns:
        target_col = col
        break

if target_col:
    predict_cols = [
        'Greutate', 'Lungime_urechi', 'Ureche_lăsată', 'Culoare',
        'Vârstă', 'Calitate_blană', 'Formă_corp', 'Apare_gușa', 'Sănătate', 'Sex'
    ]

    train_clean = df_train.dropna(subset=[target_col])
    X_train_original = train_clean[predict_cols]
    y_train = train_clean[target_col]
    X_test_original = df_test[predict_cols]

    imputer = SimpleImputer(strategy='median')
    X_train_imp = imputer.fit_transform(X_train_original)
    X_test_imp = imputer.transform(X_test_original)

    model = GradientBoostingRegressor(
        n_estimators=400,
        learning_rate=0.03,
        max_depth=4,
        random_state=42
    )
    model.fit(X_train_imp, y_train)

    predictions = model.predict(X_test_imp)
    df_test['Predicted_Score'] = np.clip(predictions, 0, 100)

else:
    df_test['Predicted_Score'] = 50


output = []
output.append({'subtaskID': 1, 'datapointID': 1, 'answer': num_rabbits})
for idx, row in df_test.iterrows():
    output.append({'subtaskID': 2, 'datapointID': row['ID'], 'answer': row['Cluster']})
    output.append({'subtaskID': 3, 'datapointID': row['ID'], 'answer': row['Predicted_Score']})

pd.DataFrame(output).to_csv('output.csv', index=False)